blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/VintageTechie/cosmic-ext-applet-tempest/discussions
    about: For questions, use Discussions instead of Issues